In [1]:
import pandas as pd
df = pd.read_csv('data/score.csv', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
df2=df.groupby('학교').get_group('능남고')
df2.to_csv('data/능남고.csv')

In [3]:
df.groupby('학교').get_group('북산고')

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python
2번    정대만  북산고  184  40  35   50  55  25        Java
3번    송태섭  북산고  168  80  75   70  80  75  Javascript
4번    서태웅  북산고  187  40  60   70  75  80         NaN
5번    강백호  북산고  188  15  20   10  35  10         NaN

In [4]:
df.groupby('학교')['키'].mean().to_frame('평균키')

            평균키
학교
능남고  193.333333
북산고  184.800000

In [5]:
df.groupby('학교')[['국어','영어','수학']].mean()

            국어         영어         수학
학교
능남고  78.333333  83.333333  76.666667
북산고  53.000000  55.000000  60.000000

In [6]:
df3 = df.groupby('학교')[['국어','영어','수학']].mean()
df3.columns = ['국어평균','영어평균','수학평균']
df3

          국어평균       영어평균       수학평균
학교
능남고  78.333333  83.333333  76.666667
북산고  53.000000  55.000000  60.000000

In [7]:
df['학년'] = [3,3,2,1,1,3,2,2]
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python   3
2번    정대만  북산고  184   40   35   50  55  25        Java   3
3번    송태섭  북산고  168   80   75   70  80  75  Javascript   2
4번    서태웅  북산고  187   40   60   70  75  80         NaN   1
5번    강백호  북산고  188   15   20   10  35  10         NaN   1
6번    변덕규  능남고  202   80  100   95  85  80           C   3
7번    황태산  능남고  188   55   65   45  40  35      PYTHON   2
8번    윤대협  능남고  190  100   85   90  95  95          C#   2

In [8]:
df4=df.groupby(['학교', '학년'])['키'].mean().to_frame('평균키')
df4

          평균키
학교  학년
능남고 2   189.0
    3   202.0
북산고 1   187.5
    2   168.0
    3   190.5

In [9]:
df2.sort_values('키', ascending=False) #키 기준 내림차순 정렬

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
6번    변덕규  능남고  202   80  100  95  85  80       C
8번    윤대협  능남고  190  100   85  90  95  95      C#
7번    황태산  능남고  188   55   65  45  40  35  PYTHON

In [10]:
df2.sort_index(ascending=False)

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
8번    윤대협  능남고  190  100   85  90  95  95      C#
7번    황태산  능남고  188   55   65  45  40  35  PYTHON
6번    변덕규  능남고  202   80  100  95  85  80       C

In [13]:
df4.loc['능남고',3]

평균키    202.0
Name: (능남고, 3), dtype: float64

In [14]:
df.groupby('학교').size().to_frame('학생수')

     학생수
학교
능남고    3
북산고    5

In [15]:
df['SW특기'] = df['SW특기'].str.capitalize()
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python   3
2번    정대만  북산고  184   40   35   50  55  25        Java   3
3번    송태섭  북산고  168   80   75   70  80  75  Javascript   2
4번    서태웅  북산고  187   40   60   70  75  80         NaN   1
5번    강백호  북산고  188   15   20   10  35  10         NaN   1
6번    변덕규  능남고  202   80  100   95  85  80           C   3
7번    황태산  능남고  188   55   65   45  40  35      Python   2
8번    윤대협  능남고  190  100   85   90  95  95          C#   2

In [16]:
df.loc['4번', 'SW특기'] = 'java'
df.loc['5번', 'SW특기'] = 'python'
df['SW특기'] = df['SW특기'].str.capitalize()
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python   3
2번    정대만  북산고  184   40   35   50  55  25        Java   3
3번    송태섭  북산고  168   80   75   70  80  75  Javascript   2
4번    서태웅  북산고  187   40   60   70  75  80        Java   1
5번    강백호  북산고  188   15   20   10  35  10      Python   1
6번    변덕규  능남고  202   80  100   95  85  80           C   3
7번    황태산  능남고  188   55   65   45  40  35      Python   2
8번    윤대협  능남고  190  100   85   90  95  95          C#   2

In [17]:
df.groupby('SW특기').size().to_frame('인원수')

            인원수
SW특기
C             1
C#            1
Java          2
Javascript    1
Python        3

In [18]:
#학교별 학생수, SW특기자수
df2=df.groupby('학교').count()[['이름', 'SW특기']]
df2.columns = ['학생수', 'SW특기자 수']
df2

     학생수  SW특기자 수
학교
능남고    3        3
북산고    5        5

In [19]:
df['SW특기'].unique()

array(['Python', 'Java', 'Javascript', 'C', 'C#'], dtype=object)

In [23]:
df5 = df['SW특기'].value_counts(normalize=True).to_frame('proportion')
df5['퍼센트'] = (df5['proportion'] * 100).round(2)
df5 # 소수점 둘째자리까지 표시

            proportion   퍼센트
SW특기
Python           0.375  37.5
Java             0.250  25.0
Javascript       0.125  12.5
C                0.125  12.5
C#               0.125  12.5

In [24]:
df.groupby('SW특기').size()

SW특기
C             1
C#            1
Java          2
Javascript    1
Python        3
dtype: int64

In [27]:
df.groupby(['학교','SW특기']).size().to_frame('인원수')
df.to_excel('data/학교별SW특기인원수.xlsx', index=False)

In [ ]:
df.groupby('학교')['SW특기'].unique().to_frame()

In [ ]:
df_info = df[['이름', '학교', '학년', '키', 'SW특기']]
df_info.to_csv('data/학생정보.csv')

In [ ]:
df_score = df.loc[:, '국어':'사회']
df_score.to_csv('data/학생성적.csv')

In [ ]:
df_score = pd.read_csv('data/학생성적.csv')
df_score['지원번호']=df_score['지원번호'].str.replace('번', '')
df_score['지원번호']=df_score['지원번호'].apply(lambda x:int(x))
df_score.to_csv('data/학생성적.csv', index=False)

In [ ]:
df_score = pd.read_csv('data/학생성적.csv')
df_score